/**:
  ros__parameters:
    # ---- Detection ----
    image_transport: raw
    family: "36h11"
    size: 0.16
    max_hamming: 1

    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.8
      debug: false

    pose_estimation_method: pnp

    # ---- Tags (list) ----
    #tag:
      #ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      #frames: ["world_reference", "target_1", "target_2", "target_3", "target_4", "target_5", "target_6", "target_7", "target_8", "target_9", "target_10"]
      #sizes: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1] 

    profile: false
    use_sim_time: false
